/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Action: typeof import('./../src/components/Table/components/Action.vue')['default'];
    AppLoading: typeof import('./../src/components/Common/AppLoading.vue')['default'];
    copy: typeof import('./../src/components/VxeTable/src/components/TableAction copy.vue')['default'];
    DarkModeContainer: typeof import('./../src/components/Common/DarkModeContainer.vue')['default'];
    DarkModeSwitch: typeof import('./../src/components/Common/DarkModeSwitch.vue')['default'];
    Form: typeof import('./../src/components/Form/index.vue')['default'];
    FormAction: typeof import('./../src/components/Form/components/FormAction.vue')['default'];
    FormItemComponent: typeof import('./../src/components/Form/components/FormItemComponent.vue')['default'];
    HoverContainer: typeof import('./../src/components/Common/HoverContainer.vue')['default'];
    NaiveProvider: typeof import('./../src/components/Common/NaiveProvider.vue')['default'];
    NAvatar: typeof import('naive-ui')['NAvatar'];
    NBackTop: typeof import('naive-ui')['NBackTop'];
    NButton: typeof import('naive-ui')['NButton'];
    NColorPicker: typeof import('naive-ui')['NColorPicker'];
    NConfigProvider: typeof import('naive-ui')['NConfigProvider'];
    NDataTable: typeof import('naive-ui')['NDataTable'];
    NDialogProvider: typeof import('naive-ui')['NDialogProvider'];
    NDivider: typeof import('naive-ui')['NDivider'];
    NDrawer: typeof import('naive-ui')['NDrawer'];
    NDrawerContent: typeof import('naive-ui')['NDrawerContent'];
    NDropdown: typeof import('naive-ui')['NDropdown'];
    NDynamicTags: typeof import('naive-ui')['NDynamicTags'];
    NForm: typeof import('naive-ui')['NForm'];
    NFormItem: typeof import('naive-ui')['NFormItem'];
    NGradientText: typeof import('naive-ui')['NGradientText'];
    NGrid: typeof import('naive-ui')['NGrid'];
    NGridItem: typeof import('naive-ui')['NGridItem'];
    NIcon: typeof import('naive-ui')['NIcon'];
    NImage: typeof import('naive-ui')['NImage'];
    NInput: typeof import('naive-ui')['NInput'];
    NInputNumber: typeof import('naive-ui')['NInputNumber'];
    NLayout: typeof import('naive-ui')['NLayout'];
    NLayoutContent: typeof import('naive-ui')['NLayoutContent'];
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader'];
    NLayoutSider: typeof import('naive-ui')['NLayoutSider'];
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider'];
    NMenu: typeof import('naive-ui')['NMenu'];
    NMessageProvider: typeof import('naive-ui')['NMessageProvider'];
    NModal: typeof import('naive-ui')['NModal'];
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider'];
    NPopconfirm: typeof import('naive-ui')['NPopconfirm'];
    NScrollbar: typeof import('naive-ui')['NScrollbar'];
    NSelect: typeof import('naive-ui')['NSelect'];
    NSpace: typeof import('naive-ui')['NSpace'];
    NSwitch: typeof import('naive-ui')['NSwitch'];
    NTabPane: typeof import('naive-ui')['NTabPane'];
    NTabs: typeof import('naive-ui')['NTabs'];
    NTooltip: typeof import('naive-ui')['NTooltip'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    Table: typeof import('./../src/components/Table/index.vue')['default'];
    TableAction: typeof import('./../src/components/VxeTable/src/components/TableAction.vue')['default'];
    TableAction2: typeof import('./../src/components/Table/components/TableAction2.vue')['default'];
    Toolbars: typeof import('./../src/components/Table/components/Toolbars.vue')['default'];
  }
}
